title: longbikeride.net
email: marco@gallotta.co.za
description: >-
  Long distance cycling adventures of Moinudin.
url: "http://www.longbikeride.net"
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: marcog
github_username:  marcogallotta
include: ["_pages"]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: true
      comments: true
      share: true
      related: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

analytics:
  provider: "google"
  google:
    tracking_id: UA-35274809-2
    anonymize_ip: false

comments:
  provider: "disqus"
  disqus:
    shortname: "longbikeride-1"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-include-cache
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

